version: "3"
services:
  db:
    image: mysql:8.0.28
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./.data/db:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
  rails:
    build: rails/
    command: /bin/bash -c "rm -f tmp/pids/server.pid && bin/dev"
    volumes:
      - ./back:/app:cached
    depends_on:
      - db
    ports:
      - 3000:3000
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
