version: "3"
services:
  db:
    image: mysql:8.0.28
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./.data/db:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
  rails:
    build: rails/
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./rails:/app:cached
    depends_on:
      - db
    ports:
      - 3000:3000
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
